spring:
  datasource:
    url: jdbc:postgresql://192.168.0.14:5432/testdb
    username: auto_woody
    password: woody

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false

  devtools:
    livereload:
      enabled: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB


logging:
  level:
    org:
      hibernate:
        SQL: debug
#        type:
#          descriptor:
#            sql:
#              BasicBinder: trace
server:
  tomcat:
    max-http-form-post-size: 10MB
    max-swallow-size: 10MB
